//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.ClientReader.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PalladiumDwh.ClientReader.Infrastructure.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientArtExtractError as
        ///SELECT        *
        ///FROM            TempPatientArtExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientArtExtractError {
            get {
                return ResourceManager.GetString("vTempPatientArtExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientArtExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientArtExtractError.PatientPK,dbo.vTempPatientArtExtractError.FacilityId,
        ///                         dbo.vTempPatientArtExtractError.PatientID, dbo.vTempPatientArtExtractError.SiteCode, dbo.vTempPatientArtExtractError.FacilityName, dbo.ValidationError.RecordId
        ///FROM            dbo.vTempPa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientArtExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientArtExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientBaselinesExtractError as
        ///SELECT        *
        ///FROM            TempPatientBaselinesExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientBaselinesExtractError {
            get {
                return ResourceManager.GetString("vTempPatientBaselinesExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientBaselinesExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientBaselinesExtractError.PatientPK,dbo.vTempPatientBaselinesExtractError.FacilityId,
        ///                         dbo.vTempPatientBaselinesExtractError.PatientID, dbo.vTempPatientBaselinesExtractError.SiteCode, dbo.ValidationError.RecordId
        ///FROM            dbo.vTempPatientBaselinesEx [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientBaselinesExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientBaselinesExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientExtractError as
        ///SELECT        *
        ///FROM            TempPatientExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientExtractError {
            get {
                return ResourceManager.GetString("vTempPatientExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientExtractError.PatientPK,dbo.vTempPatientExtractError.FacilityId,
        ///                         dbo.vTempPatientExtractError.PatientID, dbo.vTempPatientExtractError.SiteCode, dbo.vTempPatientExtractError.FacilityName, dbo.ValidationError.RecordId
        ///FROM            dbo.vTempPatientExtractError  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientLaboratoryExtractError as
        ///SELECT        *
        ///FROM            TempPatientLaboratoryExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientLaboratoryExtractError {
            get {
                return ResourceManager.GetString("vTempPatientLaboratoryExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientLaboratoryExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientLaboratoryExtractError.PatientPK,dbo.vTempPatientLaboratoryExtractError.FacilityId,
        ///                         dbo.vTempPatientLaboratoryExtractError.PatientID, dbo.vTempPatientLaboratoryExtractError.SiteCode, dbo.vTempPatientLaboratoryExtractError.FacilityName, dbo.ValidationE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientLaboratoryExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientLaboratoryExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientPharmacyExtractError as
        ///SELECT        *
        ///FROM            TempPatientPharmacyExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientPharmacyExtractError {
            get {
                return ResourceManager.GetString("vTempPatientPharmacyExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientPharmacyExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientPharmacyExtractError.PatientPK,dbo.vTempPatientPharmacyExtractError.FacilityId,
        ///                         dbo.vTempPatientPharmacyExtractError.PatientID, dbo.vTempPatientPharmacyExtractError.SiteCode,  dbo.ValidationError.RecordId
        ///FROM            dbo.vTempPatientPharmacyExtract [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientPharmacyExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientPharmacyExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientStatusExtractError as
        ///SELECT        *
        ///FROM            TempPatientStatusExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientStatusExtractError {
            get {
                return ResourceManager.GetString("vTempPatientStatusExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientStatusExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientStatusExtractError.PatientPK,dbo.vTempPatientStatusExtractError.FacilityId,
        ///                         dbo.vTempPatientStatusExtractError.PatientID, dbo.vTempPatientStatusExtractError.SiteCode, dbo.vTempPatientStatusExtractError.FacilityName, dbo.ValidationError.RecordId
        ///FROM      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientStatusExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientStatusExtractErrorSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create view vTempPatientVisitExtractError as
        ///SELECT        *
        ///FROM            TempPatientVisitExtract
        ///WHERE        (CheckError = 1).
        /// </summary>
        internal static string vTempPatientVisitExtractError {
            get {
                return ResourceManager.GetString("vTempPatientVisitExtractError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW vTempPatientVisitExtractErrorSummary
        ///AS
        ///SELECT        dbo.ValidationError.Id, dbo.Validator.Extract, dbo.Validator.Field, dbo.Validator.Type, dbo.Validator.Summary, dbo.ValidationError.DateGenerated, dbo.vTempPatientVisitExtractError.PatientPK,dbo.vTempPatientVisitExtractError.FacilityId,
        ///                         dbo.vTempPatientVisitExtractError.PatientID, dbo.vTempPatientVisitExtractError.SiteCode, dbo.vTempPatientVisitExtractError.FacilityName, dbo.ValidationError.RecordId
        ///FROM            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string vTempPatientVisitExtractErrorSummary {
            get {
                return ResourceManager.GetString("vTempPatientVisitExtractErrorSummary", resourceCulture);
            }
        }
    }
}
