// <auto-generated />
namespace PalladiumDwh.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ActionRegistas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActionRegistas));
        
        string IMigrationMetadata.Id
        {
            get { return "202006031512230_ActionRegistas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
