// <auto-generated />
namespace PalladiumDwh.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewCT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewCT));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020616497_NewCT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
