namespace PalladiumDwh.Infrastructure.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class AddedDateCreatedAndModified : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.AllergiesChronicIllnessExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.AllergiesChronicIllnessExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.ContactListingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.ContactListingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.CovidExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.CovidExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.DefaulterTracingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.DefaulterTracingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.DepressionScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.DepressionScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.DrugAlcoholScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.DrugAlcoholScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.EnhancedAdherenceCounsellingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.EnhancedAdherenceCounsellingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.GbvScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.GbvScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.IptExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.IptExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.OtzExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.OtzExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.OvcExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.OvcExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientAdverseEventExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientAdverseEventExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientArtExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientArtExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientBaselinesExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientBaselinesExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientLaboratoryExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientLaboratoryExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientPharmacyExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientPharmacyExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientStatusExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientStatusExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.PatientVisitExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.PatientVisitExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageAdverseEventExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageAdverseEventExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageAllergiesChronicIllnessExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageAllergiesChronicIllnessExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageArtExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageArtExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageBaselineExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageBaselineExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageContactListingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageContactListingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageCovidExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageCovidExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageDefaulterTracingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageDefaulterTracingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageDepressionScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageDepressionScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageDrugAlcoholScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageDrugAlcoholScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageEnhancedAdherenceCounsellingExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageEnhancedAdherenceCounsellingExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageGbvScreeningExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageGbvScreeningExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageIptExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageIptExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageLaboratoryExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageLaboratoryExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageOtzExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageOtzExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageOvcExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageOvcExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StagePatientExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StagePatientExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StagePharmacyExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StagePharmacyExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageStatusExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageStatusExtract", "Date_Last_Modified", c => c.DateTime());
            AddColumn("dbo.StageVisitExtract", "Date_Created", c => c.DateTime());
            AddColumn("dbo.StageVisitExtract", "Date_Last_Modified", c => c.DateTime());
        }
        
        public override void Down()
        {
            DropColumn("dbo.StageVisitExtract", "Date_Last_Modified");
            DropColumn("dbo.StageVisitExtract", "Date_Created");
            DropColumn("dbo.StageStatusExtract", "Date_Last_Modified");
            DropColumn("dbo.StageStatusExtract", "Date_Created");
            DropColumn("dbo.StagePharmacyExtract", "Date_Last_Modified");
            DropColumn("dbo.StagePharmacyExtract", "Date_Created");
            DropColumn("dbo.StagePatientExtract", "Date_Last_Modified");
            DropColumn("dbo.StagePatientExtract", "Date_Created");
            DropColumn("dbo.StageOvcExtract", "Date_Last_Modified");
            DropColumn("dbo.StageOvcExtract", "Date_Created");
            DropColumn("dbo.StageOtzExtract", "Date_Last_Modified");
            DropColumn("dbo.StageOtzExtract", "Date_Created");
            DropColumn("dbo.StageLaboratoryExtract", "Date_Last_Modified");
            DropColumn("dbo.StageLaboratoryExtract", "Date_Created");
            DropColumn("dbo.StageIptExtract", "Date_Last_Modified");
            DropColumn("dbo.StageIptExtract", "Date_Created");
            DropColumn("dbo.StageGbvScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.StageGbvScreeningExtract", "Date_Created");
            DropColumn("dbo.StageEnhancedAdherenceCounsellingExtract", "Date_Last_Modified");
            DropColumn("dbo.StageEnhancedAdherenceCounsellingExtract", "Date_Created");
            DropColumn("dbo.StageDrugAlcoholScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.StageDrugAlcoholScreeningExtract", "Date_Created");
            DropColumn("dbo.StageDepressionScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.StageDepressionScreeningExtract", "Date_Created");
            DropColumn("dbo.StageDefaulterTracingExtract", "Date_Last_Modified");
            DropColumn("dbo.StageDefaulterTracingExtract", "Date_Created");
            DropColumn("dbo.StageCovidExtract", "Date_Last_Modified");
            DropColumn("dbo.StageCovidExtract", "Date_Created");
            DropColumn("dbo.StageContactListingExtract", "Date_Last_Modified");
            DropColumn("dbo.StageContactListingExtract", "Date_Created");
            DropColumn("dbo.StageBaselineExtract", "Date_Last_Modified");
            DropColumn("dbo.StageBaselineExtract", "Date_Created");
            DropColumn("dbo.StageArtExtract", "Date_Last_Modified");
            DropColumn("dbo.StageArtExtract", "Date_Created");
            DropColumn("dbo.StageAllergiesChronicIllnessExtract", "Date_Last_Modified");
            DropColumn("dbo.StageAllergiesChronicIllnessExtract", "Date_Created");
            DropColumn("dbo.StageAdverseEventExtract", "Date_Last_Modified");
            DropColumn("dbo.StageAdverseEventExtract", "Date_Created");
            DropColumn("dbo.PatientVisitExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientVisitExtract", "Date_Created");
            DropColumn("dbo.PatientStatusExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientStatusExtract", "Date_Created");
            DropColumn("dbo.PatientPharmacyExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientPharmacyExtract", "Date_Created");
            DropColumn("dbo.PatientLaboratoryExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientLaboratoryExtract", "Date_Created");
            DropColumn("dbo.PatientBaselinesExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientBaselinesExtract", "Date_Created");
            DropColumn("dbo.PatientArtExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientArtExtract", "Date_Created");
            DropColumn("dbo.PatientAdverseEventExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientAdverseEventExtract", "Date_Created");
            DropColumn("dbo.OvcExtract", "Date_Last_Modified");
            DropColumn("dbo.OvcExtract", "Date_Created");
            DropColumn("dbo.OtzExtract", "Date_Last_Modified");
            DropColumn("dbo.OtzExtract", "Date_Created");
            DropColumn("dbo.IptExtract", "Date_Last_Modified");
            DropColumn("dbo.IptExtract", "Date_Created");
            DropColumn("dbo.GbvScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.GbvScreeningExtract", "Date_Created");
            DropColumn("dbo.PatientExtract", "Date_Last_Modified");
            DropColumn("dbo.PatientExtract", "Date_Created");
            DropColumn("dbo.EnhancedAdherenceCounsellingExtract", "Date_Last_Modified");
            DropColumn("dbo.EnhancedAdherenceCounsellingExtract", "Date_Created");
            DropColumn("dbo.DrugAlcoholScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.DrugAlcoholScreeningExtract", "Date_Created");
            DropColumn("dbo.DepressionScreeningExtract", "Date_Last_Modified");
            DropColumn("dbo.DepressionScreeningExtract", "Date_Created");
            DropColumn("dbo.DefaulterTracingExtract", "Date_Last_Modified");
            DropColumn("dbo.DefaulterTracingExtract", "Date_Created");
            DropColumn("dbo.CovidExtract", "Date_Last_Modified");
            DropColumn("dbo.CovidExtract", "Date_Created");
            DropColumn("dbo.ContactListingExtract", "Date_Last_Modified");
            DropColumn("dbo.ContactListingExtract", "Date_Created");
            DropColumn("dbo.AllergiesChronicIllnessExtract", "Date_Last_Modified");
            DropColumn("dbo.AllergiesChronicIllnessExtract", "Date_Created");
        }
    }
}
