CREATE INDEX idx_stagecols ON StagePatientExtract (SiteCode,PatientPID,FacilityId,LiveSession,LiveStage,CurrentPatientId)

CREATE INDEX idx_stagecols ON StageAdverseEventExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageAllergiesChronicIllnessExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageArtExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageBaselineExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageContactListingExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageCovidExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageDefaulterTracingExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageDepressionScreeningExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageDrugAlcoholScreeningExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageEnhancedAdherenceCounsellingExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageGbvScreeningExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageIptExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageLaboratoryExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageOtzExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageOvcExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)

CREATE INDEX idx_stagecols ON StagePharmacyExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageStatusExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
CREATE INDEX idx_stagecols ON StageVisitExtract (SiteCode,PatientPK,FacilityId,LiveSession,LiveStage,CurrentPatientId)
