//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Uploader.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public Facility()
        {
            this.UploadErrorLogs = new HashSet<UploadErrorLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> FacilityCode { get; set; }
        public string FacilityName { get; set; }
        public Nullable<System.DateTime> DateLoaded { get; set; }
        public Nullable<int> UploadStatus { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    
        public virtual ICollection<UploadErrorLog> UploadErrorLogs { get; set; }
    }
}
