//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Uploader.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientExtract
    {
        public PatientExtract()
        {
            this.PatientArtExtracts = new HashSet<PatientArtExtract>();
            this.PatientBaselinesExtracts = new HashSet<PatientBaselinesExtract>();
            this.PatientLaboratoryExtracts = new HashSet<PatientLaboratoryExtract>();
            this.PatientPharmacyExtracts = new HashSet<PatientPharmacyExtract>();
            this.PatientStatusExtracts = new HashSet<PatientStatusExtract>();
            this.PatientVisitExtracts = new HashSet<PatientVisitExtract>();
        }
    
        public int Id { get; set; }
        public int SiteCode { get; set; }
        public string PatientCccNumber { get; set; }
        public string FacilityName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> RegistrationAtCCC { get; set; }
        public Nullable<System.DateTime> RegistrationATPMTCT { get; set; }
        public Nullable<System.DateTime> RegistrationAtTBClinic { get; set; }
        public string PatientSource { get; set; }
        public string Region { get; set; }
        public string District { get; set; }
        public string Village { get; set; }
        public string ContactRelation { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public string MaritalStatus { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<System.DateTime> DateConfirmedHIVPositive { get; set; }
        public string PreviousARTExposure { get; set; }
        public Nullable<System.DateTime> PreviousARTStartDate { get; set; }
        public string Emr { get; set; }
        public string Project { get; set; }
        public Nullable<int> Uploaded { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    
        public virtual ICollection<PatientArtExtract> PatientArtExtracts { get; set; }
        public virtual ICollection<PatientBaselinesExtract> PatientBaselinesExtracts { get; set; }
        public virtual ICollection<PatientLaboratoryExtract> PatientLaboratoryExtracts { get; set; }
        public virtual ICollection<PatientPharmacyExtract> PatientPharmacyExtracts { get; set; }
        public virtual ICollection<PatientStatusExtract> PatientStatusExtracts { get; set; }
        public virtual ICollection<PatientVisitExtract> PatientVisitExtracts { get; set; }
    }
}
