//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Uploader.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVisitExtract
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int SiteCode { get; set; }
        public string PatientCccNumber { get; set; }
        public Nullable<int> VisitID { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string Service { get; set; }
        public string VisitType { get; set; }
        public Nullable<int> WHOStage { get; set; }
        public string WABStage { get; set; }
        public string Pregnant { get; set; }
        public Nullable<System.DateTime> LMP { get; set; }
        public Nullable<System.DateTime> EDD { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string BP { get; set; }
        public string OI { get; set; }
        public Nullable<System.DateTime> OIDate { get; set; }
        public Nullable<System.DateTime> SubstitutionFirstlineRegimenDate { get; set; }
        public string SubstitutionFirstlineRegimenReason { get; set; }
        public Nullable<System.DateTime> SubstitutionSecondlineRegimenDate { get; set; }
        public string SubstitutionSecondlineRegimenReason { get; set; }
        public Nullable<System.DateTime> SecondlineRegimenChangeDate { get; set; }
        public string SecondlineRegimenChangeReason { get; set; }
        public string Adherence { get; set; }
        public string AdherenceCategory { get; set; }
        public string FamilyPlanningMethod { get; set; }
        public string PwP { get; set; }
        public Nullable<decimal> GestationAge { get; set; }
        public Nullable<System.DateTime> NextAppointmentDate { get; set; }
        public string Emr { get; set; }
        public string Project { get; set; }
        public Nullable<int> Uploaded { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    
        public virtual PatientExtract PatientExtract { get; set; }
    }
}
