//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Uploader.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientBaselinesExtract
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int SiteCode { get; set; }
        public string PatientCccNumber { get; set; }
        public Nullable<int> eCD4 { get; set; }
        public Nullable<System.DateTime> eCD4Date { get; set; }
        public Nullable<int> eWHO { get; set; }
        public Nullable<System.DateTime> eWHODate { get; set; }
        public Nullable<int> bCD4 { get; set; }
        public Nullable<System.DateTime> bCD4Date { get; set; }
        public Nullable<int> bWHO { get; set; }
        public Nullable<System.DateTime> bWHODate { get; set; }
        public Nullable<int> lastWHO { get; set; }
        public Nullable<System.DateTime> lastWHODate { get; set; }
        public Nullable<int> lastCD4 { get; set; }
        public Nullable<System.DateTime> lastCD4Date { get; set; }
        public Nullable<int> m12CD4 { get; set; }
        public Nullable<System.DateTime> m12CD4Date { get; set; }
        public Nullable<int> m6CD4 { get; set; }
        public Nullable<System.DateTime> m6CD4Date { get; set; }
        public string Emr { get; set; }
        public string Project { get; set; }
        public Nullable<int> Uploaded { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    
        public virtual PatientExtract PatientExtract { get; set; }
    }
}
