//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Wapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientArtExtract
    {
        public int Id { get; set; }
        public int SiteCode { get; set; }
        public int PatientId { get; set; }
        public string PatientCccNumber { get; set; }
        public Nullable<decimal> AgeEnrollment { get; set; }
        public Nullable<decimal> AgeARTStart { get; set; }
        public Nullable<decimal> AgeLastVisit { get; set; }
        public string FacilityName { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string PatientSource { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> StartARTDate { get; set; }
        public Nullable<System.DateTime> PreviousARTStartDate { get; set; }
        public string PreviousARTRegimen { get; set; }
        public Nullable<System.DateTime> StartARTAtThisFacility { get; set; }
        public string StartRegimen { get; set; }
        public string StartRegimenLine { get; set; }
        public Nullable<System.DateTime> LastARTDate { get; set; }
        public string LastRegimen { get; set; }
        public string LastRegimenLine { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> ExpectedReturn { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public string ExitReason { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public string Emr { get; set; }
        public string Project { get; set; }
        public Nullable<int> Uploaded { get; set; }
    
        public virtual PatientExtract PatientExtract { get; set; }
    }
}
