//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalladiumDwh.Wapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientPharmacyExtract
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public Nullable<int> SiteCode { get; set; }
        public string PatientCccNumber { get; set; }
        public Nullable<int> VisitID { get; set; }
        public string Drug { get; set; }
        public Nullable<System.DateTime> DispenseDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string ExpectedReturn { get; set; }
        public string TreatmentType { get; set; }
        public string PeriodTaken { get; set; }
        public string ProphylaxisType { get; set; }
        public string Emr { get; set; }
        public string Project { get; set; }
        public Nullable<int> Uploaded { get; set; }
    
        public virtual PatientExtract PatientExtract { get; set; }
    }
}
